"""
RiskScore: calculates a numeric risk score (0-100) based on findings
and translates it into a qualitative risk level.
"""

from dataclasses import dataclass
from core.finding import Finding


SEVERITY_POINTS = {
    "CRITICAL": 25,
    "HIGH":     15,
    "MEDIUM":    8,
    "LOW":       3,
    "INFO":      0,
}

RISK_LEVELS = [
    (80, "CRITICAL", "red"),
    (60, "HIGH",     "orange"),
    (40, "MEDIUM",   "yellow"),
    (0,  "LOW",      "green"),
]


@dataclass
class RiskResult:
    """
    Result of the risk score calculation.

    Attributes:
        score:     Numeric score from 0 to 100.
        level:     Qualitative level: CRITICAL, HIGH, MEDIUM, LOW.
        color:     Suggested color for terminal output.
        breakdown: Finding count per severity level.
    """
    score:     int
    level:     str
    color:     str
    breakdown: dict[str, int]


def calculate(findings: list[Finding]) -> RiskResult:
    """
    Calculate the risk score from a list of findings.

    Score accumulates by adding points per finding based on severity,
    capped at 100. The qualitative level is determined by score ranges.

    Args:
        findings: List of Finding objects generated by all modules.

    Returns:
        RiskResult with score, level, color and breakdown.
    """
    breakdown: dict[str, int] = {sev: 0 for sev in SEVERITY_POINTS}

    for finding in findings:
        breakdown[finding.severity] = breakdown.get(finding.severity, 0) + 1

    raw_score = sum(
        count * SEVERITY_POINTS[sev]
        for sev, count in breakdown.items()
    )
    score = min(raw_score, 100)
    level, color = _get_level(score)

    return RiskResult(score=score, level=level, color=color, breakdown=breakdown)


def _get_level(score: int) -> tuple[str, str]:
    """Translate a numeric score to a level and color."""
    for threshold, level, color in RISK_LEVELS:
        if score >= threshold:
            return level, color
    return "LOW", "green"
